name: Market Data CI

on:
  push:
    paths:
      - 'market_data/**'
  pull_request:
    paths:
      - 'market_data/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update package lists
        run:  sudo apt update
      - name: Set up CMake and ninja
        run:  sudo apt install cmake ninja-build
      - name: Set up microservice directory run
        run: |
          cd market_data
          mkdir build
          cd build
          cmake ..
          cmake --build .
#      - name: Run CMake
#        run: cmake ..
#      - name: Build
#        run: cmake --build .
