name: Market Data CI

on:
  push:
    paths:
      - 'market_data/**'
  pull_request:
    paths:
      - 'market_data/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update package lists
        run:  sudo apt update
      - name: Set up CMake and ninja
        run:  sudo apt install cmake ninja-build
      - name: Set up microservice directory run
        run: mkdir market_data/build
      - name: Run CMake
        run: cmake .
        working-directory: ./market_data
      - name: Build
        run: cmake --build ./build
        working-directory: ./market_data
