name: Market Data CI

on:
  push:
    paths:
      - 'market_data/**'
  pull_request:
    paths:
      - 'market_data/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up C++
        uses: lukka/run-cmake@v2
        with:
          cmakeListsOrSettingsJson: 'market_data/CMakeLists.txt'
      - name: Build
        run: cmake --build . --target all -- -j 1
